version: '3.1'

volumes:
    db_vol:

services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "WebEngeneeringExercise1"
            ACCEPT_EULA: "Y"

