// <auto-generated />
using System;
using E04RepetitionDatabase.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E04RepetitionDatabase.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E04RepetitionDatabase.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73c31f76-e39e-4248-9c18-66a08a5c62c9"),
                            Text = "Note 1"
                        },
                        new
                        {
                            Id = new Guid("73c31f76-e39e-4248-9c18-66a08a5c62d0"),
                            Text = "Note 2"
                        },
                        new
                        {
                            Id = new Guid("73c31f76-e39e-4248-9c18-66a08a5c62d1"),
                            Text = "Note 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
