// <auto-generated />
using System;
using E06RepetitionRest.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace E06RepetitionGrpc.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220531065122_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("E06RepetitionRest.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cp")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sws")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = new Guid("73c31f76-e39e-4248-9c18-66a08a5c62c9"),
                            Cp = 5,
                            Name = "MC1",
                            Sws = 8
                        },
                        new
                        {
                            Id = new Guid("73c31f76-e39e-4248-9c18-66a08a5c62d0"),
                            Cp = 5,
                            Name = "WE1",
                            Sws = 8
                        },
                        new
                        {
                            Id = new Guid("73c31f76-e39e-4248-9c18-66a08a5c62d1"),
                            Cp = 5,
                            Name = "VRAR",
                            Sws = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
